[package]
name = "ort-sys"
description = "Unsafe Rust bindings for ONNX Runtime 1.16 - Optimize and Accelerate Machine Learning Inferencing"
version = "2.0.0-alpha.0"
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pykeio/ort"
documentation = "https://ort.pyke.io/"
keywords = [ "machine-learning", "ai", "ml" , "sys"]
categories = [ "algorithms", "mathematics", "science" ]
authors = [
	"pyke.io <contact@pyke.io>"
]
include = [ "src/", "build.rs", "LICENSE-APACHE", "LICENSE-MIT" ]

[features]
default = []
download-binaries = [ "ureq", "zip" ]
load-dynamic = []
copy-dylibs = []
cuda = []
tensorrt = []
rocm = []

[build-dependencies]
ureq = { version = "2.1", optional = true, default-features = false, features = [ "tls" ] }
zip = { version = "0.6", optional = true, default-features = false, features = [ "deflate" ] }

[target.'cfg(not(target_os = "windows"))'.build-dependencies]
flate2 = "1.0"
tar = "0.4"
